- hosts: all
  remote_user: vagrant
  become: yes

  tasks:
          - name: Instalando o Htop
            apt:
              name: htop
              state: present

          - name: Criando usuario Analista
            user: 
              name: analista
              state: present

          - name: Ajustando o timezone do Servidor
            timezone:
              name: America/Sao_Paulo

